name: CI_CD_SITE

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/B3.Cdb/B3.Cdb.Site/**'
      - '.github/workflows/build-and-deploy-site.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/B3.Cdb/B3.Cdb.Site/**'
      - '.github/workflows/build-and-deploy-site.yml'
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set TAG environment variable
        run: echo TAG=$(echo $GITHUB_SHA | head -c7) >> $GITHUB_ENV

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker Image
        env:
          TAG: ${{ env.TAG }}
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/b3-cdb-site:${{ env.TAG }} -f src/B3.Cdb/B3.Cdb.Site/B3CdbSite/Dockerfile src/B3.Cdb/B3.Cdb.Site/B3CdbSite

      - name: Push Docker Image
        env:
          TAG: ${{ env.TAG }}
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/b3-cdb-site:${{ env.TAG }}

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Verify TAG variable in Deploy
        env:
          TAG: ${{ env.TAG }}
        run: echo ${{ env.TAG }}
    
      - name: Azure Web App Deploy
        env:
          TAG: ${{ env.TAG }}
        uses: azure/webapps-deploy@v2
        with:
          app-name: "b3-cdb-site"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_SITE }}
          images: '${{ secrets.ACR_LOGIN_SERVER }}/b3-cdb-site:${{ env.TAG }}'

