name: CI_CD_PRD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore src/B3.Cdb/B3.Cdb.sln

      - name: Build and publish using publish profile
        run: |
          msbuild src/B3.Cdb/B3.Cdb.Api/B3.Cdb.Api.csproj /p:DeployOnBuild=true /p:PublishProfile=Azure /p:Configuration=Release /p:Platform="AnyCPU" /p:WebPublishMethod=Package /p:PackageLocation="${{ github.workspace }}\publish" /v:detailed

      - name: List published artifacts
        run: dir ${{ github.workspace }}\publish

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: B3CdbApi
          path: ${{ github.workspace }}\publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: B3CdbApi
          path: ./downloaded_artifacts

      - name: List downloaded artifacts
        run: |
          if (Test-Path './downloaded_artifacts') {
            Get-ChildItem -Path './downloaded_artifacts' -Recurse
          } else {
            echo "No downloaded artifacts found."
          }

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: b3-cdb-api
          slot-name: production
          package: ./downloaded_artifacts/B3.Cdb.Api.zip
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
