name: CI_CD_SITE

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/B3.Cdb/B3.Cdb.Site/**'
      - '.github/workflows/build-and-deploy-site.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/B3.Cdb/B3.Cdb.Site/**'
      - '.github/workflows/build-and-deploy-site.yml'
  workflow_dispatch:

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  AZURE_PUBLISH_PROFILE_SITE: ${{ secrets.AZURE_PUBLISH_PROFILE_SITE }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set TAG environment variable
        id: set_tag
        run: echo "TAG=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_ENV

      - name: Verify TAG variable in Build
        run: echo $TAG

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/b3-cdb-site:$TAG -f src/B3.Cdb/B3.Cdb.Site/B3CdbSite/Dockerfile src/B3.Cdb/B3.Cdb.Site/B3CdbSite

      - name: Push Docker Image
        run: |
          docker push ${{ env.ACR_LOGIN_SERVER }}/b3-cdb-site:$TAG

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Verify TAG variable in Deploy
        run: echo $TAG
    
      - name: Azure Web App Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: "b3-cdb-site"
          publish-profile: ${{ env.AZURE_PUBLISH_PROFILE_SITE }}
          images: '${{ env.ACR_LOGIN_SERVER }}/b3-cdb-site:$TAG'
