name: CI_CD_SITE

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/B3.Cdb/B3.Cdb.Site/**'
      - '.github/workflows/build-and-deploy-site.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/B3.Cdb/B3.Cdb.Site/**'
      - '.github/workflows/build-and-deploy-site.yml'
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/b3-cdb-site:latest -f src/B3.Cdb/B3.Cdb.Site/B3CdbSite/Dockerfile src/B3.Cdb/B3.Cdb.Site/B3CdbSite

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/b3-cdb-site:latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Azure Web App Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: "b3-cdb-site"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_SITE }}
          images: '${{ secrets.ACR_LOGIN_SERVER }}/b3-cdb-site:latest'
